name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: sh0wer1ee
          template: classic
          base: activity, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_ignored: html, css
          repositories_forks: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_lines: yes
          plugin_lines_history_limit: 0
          plugin_traffic: yes
